INSERT INTO streakdb.product (company_id, name, description, category, price) VALUES
                                                                         (1, 'Big Burger', 'A juicy big burger with cheese', 'BURGER', 8.99),
                                                                         (3, 'Spicy Pizza', 'Pizza with extra chili and pepperoni', 'PIZZA', 12.50),
                                                                         (2, 'Classic Gyros', 'Greek-style gyros with tzatziki', 'GYROS', 9.75),
                                                                         (5, 'Cheese Pizza', 'Mozzarella and tomato base', 'PIZZA', 10.00),
                                                                         (7, 'Double Burger', 'Two beef patties and bacon', 'BURGER', 11.25),
                                                                         (4, 'Chicken Gyros', 'Grilled chicken with pita bread', 'GYROS', 8.50),
                                                                         (6, 'BBQ Burger', 'Beef burger with BBQ sauce', 'BURGER', 9.99),
                                                                         (2, 'Veggie Pizza', 'Loaded with fresh vegetables', 'PIZZA', 10.75),
                                                                         (8, 'Lamb Gyros', 'Lamb meat with fresh herbs', 'GYROS', 10.99),
                                                                         (9, 'Mushroom Pizza', 'Pizza with mushrooms and cream', 'PIZZA', 11.00),
                                                                         (10, 'Crispy Chicken Burger', 'Breaded chicken patty burger', 'BURGER', 9.50),
                                                                         (1, 'Pepperoni Pizza', 'Classic pepperoni pizza', 'PIZZA', 12.00),
                                                                         (3, 'Falafel Gyros', 'Vegetarian gyros with falafel', 'GYROS', 8.99),
                                                                         (5, 'Triple Burger', 'Three patties madness', 'BURGER', 13.50),
                                                                         (6, 'Hawaiian Pizza', 'Pizza with pineapple and ham', 'PIZZA', 11.25),
                                                                         (7, 'Pita Gyros', 'Traditional pita wrapped gyros', 'GYROS', 9.00),
                                                                         (2, 'Chili Burger', 'Spicy burger with jalapeños', 'BURGER', 10.75),
                                                                         (9, 'Four Cheese Pizza', 'Pizza with four types of cheese', 'PIZZA', 12.50),
                                                                         (10, 'Gyros Plate', 'Gyros served on a plate with fries', 'GYROS', 10.25),
                                                                         (4, 'Classic Burger', 'Simple burger with lettuce and tomato', 'BURGER', 8.25);
